### ISSUE TITLE
The app only displays nfcs and irs that were added through the Flipper scanning, wanting transferred from the computer doesn't show in the archive section of the app

### ISSUE THREAD

**Issue by Y0seph** [flipperdevices/Flipper-Android-App#376] opened 2022-09-17 21:41 UTC
‏

**Comment by LionZXY** [comment] 2022-09-18 15:53
Look likes duplicate of https://github.com/flipperdevices/Flipper-Android-App/issues/284

**Closed by LionZXY** 2022-09-18 15:53 UTC
